# Generated by Django 6.0.3 on 2026-03-23 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
        ),
        migrations.CreateModel(
            name='Organograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vigencia', models.DateField(blank=True, null=True)),
                ('documento_aprovacao', models.FileField(blank=True, null=True, upload_to='documentos_aprovacao/')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('OFICIAL', 'Oficial'), ('HISTORICO', 'Histórico')], default='RASCUNHO', max_length=20)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organogramas', to='core.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.CharField(max_length=255, verbose_name='Nome da Unidade Organizacional')),
                ('sigla_unidade', models.CharField(max_length=50, verbose_name='Sigla da Unidade')),
                ('cargo_funcao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo ou Função Relacionada')),
                ('sigla_cargo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla do Cargo/Função')),
                ('organograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.organograma')),
                ('unidade_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_unidades', to='core.unit')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
