# Generated by Django 6.0.3 on 2026-03-23 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organograma',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('OFICIAL', 'Oficial'), ('HISTORICO', 'Histórico'), ('PROPOSTA', 'Proposta de Alteração')], default='RASCUNHO', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitacaoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(verbose_name='Justificativa da Alteração')),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='EM_ANALISE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('organograma_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_origem', to='core.organograma')),
                ('organograma_proposto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_proposta', to='core.organograma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração',
                'verbose_name_plural': 'Solicitações de Alteração',
            },
        ),
    ]
