# Generated by Django 6.0.3 on 2026-03-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_unit_options_unit_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cargo/Função')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Cargo/Função',
                'verbose_name_plural': 'Cargos/Funções',
            },
        ),
        migrations.CreateModel(
            name='TipoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de Departamento')),
            ],
            options={
                'verbose_name': 'Tipo de Unidade',
                'verbose_name_plural': 'Tipos de Unidades',
            },
        ),
        migrations.AlterField(
            model_name='unit',
            name='cargo_funcao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo ou Função Relacionada (Antigo)'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='sigla_cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla do Cargo/Função (Antigo)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='cargo_funcao_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cargofuncao', verbose_name='Cargo ou Função Relacionada'),
        ),
        migrations.AddField(
            model_name='unit',
            name='tipo_unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipounidade', verbose_name='Tipo de Departamento'),
        ),
    ]
