# Generated by Django 6.0.3 on 2026-03-23 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cargofuncao_tipounidade_alter_unit_cargo_funcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipounidade',
            name='cargo_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cargofuncao', verbose_name='Cargo Ocupante Padrão'),
        ),
    ]
