# Generated by Django 6.0.3 on 2026-03-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tipounidade_cargo_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='organograma',
            name='nome_documento_aprovacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Documento de Aprovação'),
        ),
    ]
