# Generated by Django 6.0.3 on 2026-03-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='source_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_unidade', to='core.unit', verbose_name='Unidade Origem (para Propostas)'),
        ),
    ]
