# Generated by Django 6.0.3 on 2026-03-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_unit_source_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='ligacao_indireta',
            field=models.BooleanField(default=False, help_text='A linha de conexão com o superior será tracejada.', verbose_name='Ligação Indireta'),
        ),
        migrations.AddField(
            model_name='unit',
            name='organograma_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_vinculadas', to='core.organograma', verbose_name='Vincular a outro Organograma'),
        ),
    ]
