# Generated by Django 6.0.3 on 2026-03-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_unit_ligacao_indireta_unit_organograma_vinculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='estilo_caixinha',
            field=models.CharField(choices=[('PADRAO', 'Padrão'), ('GRADE_CAMPI', 'Grade de Unidades Descentralizadas')], default='PADRAO', max_length=20, verbose_name='Estilo da Caixinha'),
        ),
    ]
