# Generated by Django 6.0.3 on 2026-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_unit_estilo_caixinha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='estilo_caixinha',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='organograma_vinculado',
        ),
        migrations.AddField(
            model_name='organograma',
            name='organogramas_vinculados',
            field=models.ManyToManyField(blank=True, related_name='vinculados_por', to='core.organograma', verbose_name='Organogramas Vinculados'),
        ),
    ]
