# Generated by Django 6.0.3 on 2026-03-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_unit_estilo_caixinha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='sigla_unidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla da Unidade'),
        ),
    ]
