# Generated by Django 6.0.3 on 2026-03-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_unit_sigla_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_agrupamento',
            field=models.BooleanField(default=False, help_text='Define se esta unidade é apenas um grupo de interface para organizar outras caixinhas.', verbose_name='É Agrupamento Visual?'),
        ),
        migrations.AddField(
            model_name='unit',
            name='oculto_no_organograma',
            field=models.BooleanField(default=False, help_text='Se marcado, esta unidade (e suas subunidades) não aparecerão na visualização pública.', verbose_name='Oculto no Organograma'),
        ),
    ]
