# Generated by Django 6.0.3 on 2026-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_unit_is_agrupamento_unit_oculto_no_organograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='layout_filhos',
            field=models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical')], default='V', help_text='Define se as subunidades serão dispostas lado a lado (Horizontal) ou empilhadas (Vertical).', max_length=1, verbose_name='Layout dos Filhos'),
        ),
    ]
