# Generated by Django 6.0.3 on 2026-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_unit_layout_filhos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='cargo_funcao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo ou Função Relacionada'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='sigla_cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla do Cargo/Função'),
        ),
    ]
