# Generated by Django 6.0.3 on 2026-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_unit_cargo_funcao_alter_unit_sigla_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organograma',
            name='link_regimento',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Regimento do Campus'),
        ),
        migrations.AddField(
            model_name='unit',
            name='atribuicoes',
            field=models.TextField(blank=True, null=True, verbose_name='Atribuições do Departamento'),
        ),
    ]
