# Generated by Django 6.0.3 on 2026-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_organograma_link_regimento_unit_atribuicoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organograma',
            name='regimento_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='regimentos/', verbose_name='Arquivo do Regimento'),
        ),
        migrations.AlterField(
            model_name='organograma',
            name='documento_aprovacao',
            field=models.FileField(blank=True, null=True, upload_to='documentos_aprovacao/', verbose_name='Arquivo da Resolução'),
        ),
        migrations.AlterField(
            model_name='organograma',
            name='nome_documento_aprovacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número/Nome da Resolução'),
        ),
    ]
