# Generated by Django 6.0.3 on 2026-03-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_organograma_regimento_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organograma',
            name='nome_regimento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Regimento Interno'),
        ),
        migrations.AlterField(
            model_name='organograma',
            name='link_regimento',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Regimento Interno'),
        ),
        migrations.AlterField(
            model_name='organograma',
            name='regimento_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='regimentos/', verbose_name='Arquivo do Regimento Interno'),
        ),
    ]
