# Generated by Django 6.0.3 on 2026-03-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_organograma_nome_regimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organograma',
            name='link_regimento',
        ),
    ]
