# Generated by Django 6.0.3 on 2026-03-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_organograma_link_regimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='organograma',
            name='regimento_geral_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='regimentos_gerais/', verbose_name='Arquivo do Regimento Geral'),
        ),
    ]
