# Generated by Django 6.0.3 on 2026-03-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_organograma_regimento_geral_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organograma',
            name='nome_regimento_geral',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Regimento Geral'),
        ),
    ]
