# Generated by Django 6.0.3 on 2026-03-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_organograma_nome_regimento_geral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloReferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Modelo')),
                ('dimensionamento', models.CharField(choices=[('150', 'Modelo 150 Servidores'), ('150_AGRI', 'Modelo 150 Agrícola'), ('90_70_AGRI', 'Modelo 90/70 Agrícola'), ('70_45', 'Modelo 70/45'), ('20_13', 'Modelo 20/13'), ('POLO', 'Polo de Inovação')], max_length=20, verbose_name='Dimensionamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('resolucao_referencia', models.CharField(default='Resolução CONSUP 44/2025', max_length=255, verbose_name='Resolução de Referência')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo Referencial',
                'verbose_name_plural': 'Modelos Referenciais',
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='dimensionamento',
            field=models.CharField(blank=True, choices=[('150', 'Modelo 150 Servidores'), ('150_AGRI', 'Modelo 150 Agrícola'), ('90_70_AGRI', 'Modelo 90/70 Agrícola'), ('70_45', 'Modelo 70/45'), ('20_13', 'Modelo 20/13'), ('POLO', 'Polo de Inovação')], max_length=20, null=True, verbose_name='Tipo de Dimensionamento'),
        ),
        migrations.CreateModel(
            name='UnitModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.CharField(max_length=255, verbose_name='Nome da Unidade Organizacional')),
                ('sigla_unidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla da Unidade')),
                ('atribuicoes', models.TextField(blank=True, null=True, verbose_name='Atribuições do Departamento')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_agrupamento', models.BooleanField(default=False, verbose_name='É Agrupamento Visual?')),
                ('layout_filhos', models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical')], default='V', max_length=1, verbose_name='Layout dos Filhos')),
                ('cargo_funcao_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cargofuncao', verbose_name='Cargo ou Função Relacionada')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.modeloreferencial')),
                ('tipo_unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipounidade', verbose_name='Tipo de Departamento')),
                ('unidade_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_unidades', to='core.unitmodelo')),
            ],
            options={
                'verbose_name': 'Unidade do Modelo',
                'verbose_name_plural': 'Unidades do Modelo',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
