# Generated by Django 6.0.3 on 2026-03-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_modeloreferencial_campus_dimensionamento_unitmodelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='dimensionamento',
            field=models.CharField(blank=True, choices=[('150', 'Modelo 150'), ('150_AGRI', 'Modelo 150 Agrícola'), ('90_70_AGRI', 'Modelo 90/70 Agrícola'), ('70_45', 'Modelo 70/45'), ('40_26', 'Modelo 40/26'), ('REITORIA', 'Reitoria'), ('POLO', 'Polo de Inovação')], max_length=20, null=True, verbose_name='Tipo de Dimensionamento'),
        ),
        migrations.AlterField(
            model_name='modeloreferencial',
            name='dimensionamento',
            field=models.CharField(choices=[('150', 'Modelo 150'), ('150_AGRI', 'Modelo 150 Agrícola'), ('90_70_AGRI', 'Modelo 90/70 Agrícola'), ('70_45', 'Modelo 70/45'), ('40_26', 'Modelo 40/26'), ('REITORIA', 'Reitoria'), ('POLO', 'Polo de Inovação')], max_length=20, verbose_name='Dimensionamento'),
        ),
    ]
