# Generated by Django 6.0.3 on 2026-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_campus_dimensionamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipounidade',
            name='permitido_apenas_reitoria',
            field=models.BooleanField(default=False, verbose_name='Permitido apenas para Reitoria'),
        ),
    ]
