# Generated by Django 6.0.3 on 2026-03-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_tipounidade_permitido_apenas_reitoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargofuncao',
            name='permitido_apenas_reitoria',
            field=models.BooleanField(default=False, verbose_name='Permitido apenas para Reitoria'),
        ),
    ]
