# Generated by Django 6.0.3 on 2026-03-27 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cargofuncao_permitido_apenas_reitoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chave', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Dimensionamento',
                'verbose_name_plural': 'Dimensionamentos',
            },
        ),
        migrations.RemoveField(
            model_name='cargofuncao',
            name='permitido_apenas_reitoria',
        ),
        migrations.RemoveField(
            model_name='tipounidade',
            name='permitido_apenas_reitoria',
        ),
        migrations.AlterField(
            model_name='campus',
            name='dimensionamento',
            field=models.CharField(blank=True, choices=[('150', 'Modelo 150'), ('150_AGRI', 'Modelo 150 Agrícola'), ('90_70_AGRI', 'Modelo 90/70 Agrícola'), ('70_45', 'Modelo 70/45'), ('40_26', 'Modelo 40/26'), ('REITORIA', 'Reitoria'), ('POLO', 'Polo de Inovação')], max_length=20, null=True, verbose_name='Tipo de Dimensionamento (Legado)'),
        ),
        migrations.AddField(
            model_name='campus',
            name='dimensionamento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dimensionamento', verbose_name='Tipo de Dimensionamento'),
        ),
        migrations.AddField(
            model_name='cargofuncao',
            name='dimensionamentos_permitidos',
            field=models.ManyToManyField(blank=True, to='core.dimensionamento', verbose_name='Dimensionamentos Autorizados'),
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='dimensionamentos_permitidos',
            field=models.ManyToManyField(blank=True, to='core.dimensionamento', verbose_name='Dimensionamentos Autorizados'),
        ),
    ]
