# Generated by Django 6.0.3 on 2026-03-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_dimensionamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargofuncao',
            options={'ordering': ['nome'], 'verbose_name': 'Cargo/Função', 'verbose_name_plural': 'Cargos/Funções'},
        ),
    ]
