# Generated by Django 6.0.3 on 2026-03-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_cargofuncao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipounidade',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Unidade', 'verbose_name_plural': 'Tipos de Unidades'},
        ),
    ]
