# Generated by Django 6.0.3 on 2026-03-27 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_tipounidade_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloreferencial',
            name='dimensionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dimensionamento', verbose_name='Dimensionamento'),
        ),
    ]
