# Generated by Django 6.0.3 on 2026-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_modeloreferencial_dimensionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodelo',
            name='cargo_funcao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo ou Função Relacionada'),
        ),
        migrations.AddField(
            model_name='unitmodelo',
            name='sigla_cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla do Cargo/Função'),
        ),
    ]
