# Generated by Django 6.0.3 on 2026-03-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_unitmodelo_cargo_funcao_unitmodelo_sigla_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipounidade',
            name='selecao_cargo_livre',
            field=models.BooleanField(default=False, help_text='Quando marcado, o cargo não é preenchido automaticamente — o usuário pode escolher entre os cargos disponíveis (ex: Setor/Seção que aceitam FG-01 ou FG-02).', verbose_name='Permite Seleção Livre de Cargo'),
        ),
        migrations.AlterField(
            model_name='modeloreferencial',
            name='resolucao_referencia',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Resolução de Referência'),
        ),
    ]
