# Generated by Django 6.0.3 on 2026-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_tipounidade_selecao_cargo_livre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipounidade',
            name='apenas_modelo_referencial',
            field=models.BooleanField(default=False, help_text='Quando marcado, este tipo só aparece no construtor de Modelos Referenciais — não fica disponível no builder de organogramas de campus.', verbose_name='Exclusivo para Modelos Referenciais'),
        ),
    ]
