# Generated by Django 6.0.3 on 2026-04-13 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_tipounidade_apenas_modelo_referencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organograma',
            name='modelo_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organogramas_derivados', to='core.modeloreferencial', verbose_name='Modelo Referencial Base'),
        ),
        migrations.AddField(
            model_name='unit',
            name='origem_modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_derivadas', to='core.unitmodelo', verbose_name='Caixa Origem no Modelo'),
        ),
        migrations.CreateModel(
            name='RegrasAlteracaoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_flexibilizacao_fg', models.IntegerField(default=3, help_text='Número máximo de caixinhas contendo FGs que podem ter nomenclatura ou vinculação alteradas.', verbose_name='Limite Quantitativo de FGs (25%)')),
                ('permite_regra_transicao', models.BooleanField(default=False, help_text='Se marcado, eleva temporariamente o limite de 3 para 5 alterações para campi que estão adaptando a matriz (até atingirem 25/18 do quadro).', verbose_name='Permitir Regra de Transição (Dim. 40/26)')),
                ('prefixos_cargos_bloqueados', models.CharField(default='CD', help_text="Prefixo(s) de cargos que são intocáveis (separados por vírgula). Ex: 'CD'. Unidades com esses cargos não admitirão flexibilização.", max_length=255, verbose_name='Prefixos de Cargos Bloqueados')),
                ('prefixos_cargos_flexibilizaveis', models.CharField(default='FG', help_text="Prefixo(s) de cargos que usam a cota de flexibilidade (separados por vírgula). Ex: 'FG, FG-01, FG-02'.", max_length=255, verbose_name='Prefixos Inclusos na Contabilização')),
                ('departamentos_intocaveis', models.TextField(default='Gestão de Pessoas, Tecnologia da Informação, Assuntos Institucionais', help_text='Nomes de unidades (separados por vírgula) cuja nomenclatura é INALTERÁVEL, sendo flexível apenas a subordinação (qual caixa é sua mãe).', verbose_name='Departamentos Restritos à Mudança de Vinculação')),
                ('verificar_sufixo_anexo', models.BooleanField(default=True, help_text="Impede que o usuário remova o termo primário da unidade ao renomeá-la (Ex: 'Setor de...' não pode virar 'Núcleo de...').", verbose_name='Exigir Preservação de Prefixo (Anexo VII)')),
                ('modelo_referencial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regras_alteracao', to='core.modeloreferencial', verbose_name='Modelo Referencial')),
            ],
            options={
                'verbose_name': 'Regras de Alteração do Modelo',
                'verbose_name_plural': 'Regras de Alteração',
            },
        ),
    ]
