# Generated by Django 6.0.3 on 2026-05-04 17:05

import django.db.models.deletion
from django.db import migrations, models


def backfill_modelos(apps, schema_editor):
    Campus = apps.get_model('core', 'Campus')
    ModeloReferencial = apps.get_model('core', 'ModeloReferencial')
    Organograma = apps.get_model('core', 'Organograma')
    RegrasAlteracaoModelo = apps.get_model('core', 'RegrasAlteracaoModelo')

    for campus in Campus.objects.all():
        if campus.modelo_referencial_padrao_id:
            continue
        chave = None
        if campus.dimensionamento_fk_id:
            chave = campus.dimensionamento_fk.chave
        elif campus.dimensionamento:
            chave = campus.dimensionamento
        if not chave:
            continue
        modelo = ModeloReferencial.objects.filter(dimensionamento__chave=chave, ativo=True).order_by('id').first()
        if modelo:
            campus.modelo_referencial_padrao = modelo
            campus.save(update_fields=['modelo_referencial_padrao'])

    for organograma in Organograma.objects.select_related('campus', 'modelo_base').all():
        modelo = organograma.modelo_base or organograma.campus.modelo_referencial_padrao
        if not modelo:
            continue
        changed_fields = []
        if organograma.modelo_base_id != modelo.id:
            organograma.modelo_base = modelo
            changed_fields.append('modelo_base')
        if organograma.modelo_referencia_atualizado_em is None:
            organograma.modelo_referencia_atualizado_em = modelo.data_atualizacao
            changed_fields.append('modelo_referencia_atualizado_em')
        if changed_fields:
            organograma.save(update_fields=changed_fields)

    for regras in RegrasAlteracaoModelo.objects.select_related('modelo_referencial__dimensionamento').all():
        chave = regras.modelo_referencial.dimensionamento.chave
        base_limit = 3
        if chave in {'150', '150_AGRI'}:
            base_limit = 6
        elif chave == 'POLO':
            base_limit = 1
        regras.limite_total_alteracoes = max(regras.limite_total_alteracoes, base_limit * 2)
        for field_name in (
            'limite_renomeacao',
            'limite_mudanca_vinculo',
            'limite_alteracao_cargo',
            'limite_alteracao_tipo_unidade',
            'limite_alteracao_sigla',
            'limite_exclusao_unidade_modelo',
            'limite_inclusao_unidade_nova',
        ):
            if not getattr(regras, field_name):
                setattr(regras, field_name, base_limit)
        regras.save()


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_organograma_modelo_base_unit_origem_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='modelo_referencial_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campi_padrao', to='core.modeloreferencial', verbose_name='Modelo Referencial do Campus'),
        ),
        migrations.AddField(
            model_name='organograma',
            name='modelo_referencia_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revisão do Modelo Referencial Aplicada'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='exige_vinculo_com_modelo',
            field=models.BooleanField(default=True, verbose_name='Exigir vínculo com unidades do modelo'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='exigir_adequacao_quando_modelo_mudar',
            field=models.BooleanField(default=False, verbose_name='Exigir adequação quando o modelo mudar'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='limite_alteracao_cargo',
            field=models.IntegerField(default=3, verbose_name='Limite de alterações de cargo'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='limite_alteracao_sigla',
            field=models.IntegerField(default=3, verbose_name='Limite de alterações de sigla'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='limite_alteracao_tipo_unidade',
            field=models.IntegerField(default=3, verbose_name='Limite de alterações de tipo'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='limite_exclusao_unidade_modelo',
            field=models.IntegerField(default=3, verbose_name='Limite de exclusões de unidades do modelo'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='limite_inclusao_unidade_nova',
            field=models.IntegerField(default=3, verbose_name='Limite de inclusões de unidades novas'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='limite_mudanca_vinculo',
            field=models.IntegerField(default=3, verbose_name='Limite de mudanças de vínculo'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='limite_renomeacao',
            field=models.IntegerField(default=3, verbose_name='Limite de renomeações'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='limite_total_alteracoes',
            field=models.IntegerField(default=6, verbose_name='Limite Total de Alterações'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='permite_alteracao_cargo',
            field=models.BooleanField(default=True, verbose_name='Permite alteração de cargo'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='permite_alteracao_sigla',
            field=models.BooleanField(default=True, verbose_name='Permite alteração de sigla'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='permite_alteracao_tipo_unidade',
            field=models.BooleanField(default=True, verbose_name='Permite alteração de tipo de unidade'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='permite_exclusao_unidade_modelo',
            field=models.BooleanField(default=True, verbose_name='Permite exclusão de unidade do modelo'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='permite_inclusao_unidade_nova',
            field=models.BooleanField(default=True, verbose_name='Permite inclusão de unidade nova'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='permite_mudanca_vinculo',
            field=models.BooleanField(default=True, verbose_name='Permite mudança de vínculo'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='permite_renomeacao',
            field=models.BooleanField(default=True, verbose_name='Permite renomeação'),
        ),
        migrations.CreateModel(
            name='ExcecaoRegraAlteracaoCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_total_alteracoes', models.IntegerField(blank=True, null=True, verbose_name='Limite Total de Alterações')),
                ('exige_vinculo_com_modelo', models.BooleanField(blank=True, null=True, verbose_name='Exigir vínculo com unidades do modelo')),
                ('exigir_adequacao_quando_modelo_mudar', models.BooleanField(blank=True, null=True, verbose_name='Exigir adequação quando o modelo mudar')),
                ('permite_renomeacao', models.BooleanField(blank=True, null=True, verbose_name='Permite renomeação')),
                ('limite_renomeacao', models.IntegerField(blank=True, null=True, verbose_name='Limite de renomeações')),
                ('permite_mudanca_vinculo', models.BooleanField(blank=True, null=True, verbose_name='Permite mudança de vínculo')),
                ('limite_mudanca_vinculo', models.IntegerField(blank=True, null=True, verbose_name='Limite de mudanças de vínculo')),
                ('permite_alteracao_cargo', models.BooleanField(blank=True, null=True, verbose_name='Permite alteração de cargo')),
                ('limite_alteracao_cargo', models.IntegerField(blank=True, null=True, verbose_name='Limite de alterações de cargo')),
                ('permite_alteracao_tipo_unidade', models.BooleanField(blank=True, null=True, verbose_name='Permite alteração de tipo de unidade')),
                ('limite_alteracao_tipo_unidade', models.IntegerField(blank=True, null=True, verbose_name='Limite de alterações de tipo')),
                ('permite_alteracao_sigla', models.BooleanField(blank=True, null=True, verbose_name='Permite alteração de sigla')),
                ('limite_alteracao_sigla', models.IntegerField(blank=True, null=True, verbose_name='Limite de alterações de sigla')),
                ('permite_exclusao_unidade_modelo', models.BooleanField(blank=True, null=True, verbose_name='Permite exclusão de unidade do modelo')),
                ('limite_exclusao_unidade_modelo', models.IntegerField(blank=True, null=True, verbose_name='Limite de exclusões de unidades do modelo')),
                ('permite_inclusao_unidade_nova', models.BooleanField(blank=True, null=True, verbose_name='Permite inclusão de unidade nova')),
                ('limite_inclusao_unidade_nova', models.IntegerField(blank=True, null=True, verbose_name='Limite de inclusões de unidades novas')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecoes_regras_modelo', to='core.campus', verbose_name='Campus')),
                ('modelo_referencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecoes_campus', to='core.modeloreferencial', verbose_name='Modelo Referencial')),
            ],
            options={
                'verbose_name': 'Exceção de Regra por Campus',
                'verbose_name_plural': 'Exceções de Regra por Campus',
                'unique_together': {('modelo_referencial', 'campus')},
            },
        ),
        migrations.RunPython(backfill_modelos, noop),
    ]
