# Generated by Django 6.0.3 on 2026-05-04 17:36

from django.db import migrations, models


def migrate_legacy_hybrid_units(apps, schema_editor):
    UnitModelo = apps.get_model('core', 'UnitModelo')
    TipoUnidade = apps.get_model('core', 'TipoUnidade')
    CargoFuncao = apps.get_model('core', 'CargoFuncao')

    tipo_generico_ids = set(
        TipoUnidade.objects.filter(nome__in=['Setor ou Seção', 'Setor ou Secao']).values_list('id', flat=True)
    )
    cargo_generico_ids = set(
        CargoFuncao.objects.filter(sigla__in=['FG-01 ou FG-02', 'FG-01 OU FG-02']).values_list('id', flat=True)
    )
    tipos_permitidos = list(
        TipoUnidade.objects.filter(nome__in=['Setor', 'Seção', 'Secao']).values_list('id', flat=True)
    )
    cargos_permitidos = list(
        CargoFuncao.objects.filter(sigla__in=['FG-01', 'FG-02']).values_list('id', flat=True)
    )

    if not tipos_permitidos or not cargos_permitidos:
        return

    through_tipos = UnitModelo.tipos_resolucao_permitidos.through
    through_cargos = UnitModelo.cargos_resolucao_permitidos.through

    for unit in UnitModelo.objects.all():
        nome_upper = (unit.nome_unidade or '').upper()
        cargo_upper = (unit.cargo_funcao or '').upper()
        is_legacy_hybrid = (
            unit.tipo_unidade_id in tipo_generico_ids
            or unit.cargo_funcao_ref_id in cargo_generico_ids
            or 'SETOR OU SEÇÃO' in nome_upper
            or 'SETOR OU SECAO' in nome_upper
            or 'FG-01 OU FG-02' in cargo_upper
        )
        if not is_legacy_hybrid:
            continue

        update_fields = ['permite_resolucao_flexivel']
        unit.permite_resolucao_flexivel = True

        if unit.tipo_unidade_id in tipo_generico_ids:
            unit.tipo_unidade_id = None
            update_fields.append('tipo_unidade')

        if unit.cargo_funcao_ref_id in cargo_generico_ids:
            if not unit.cargo_funcao:
                unit.cargo_funcao = unit.cargo_funcao_ref.nome
                update_fields.append('cargo_funcao')
            unit.cargo_funcao_ref_id = None
            update_fields.append('cargo_funcao_ref')

        unit.save(update_fields=update_fields)

        for tipo_id in tipos_permitidos:
            through_tipos.objects.get_or_create(unitmodelo_id=unit.id, tipounidade_id=tipo_id)
        for cargo_id in cargos_permitidos:
            through_cargos.objects.get_or_create(unitmodelo_id=unit.id, cargofuncao_id=cargo_id)


def reverse_legacy_hybrid_units(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_campus_modelo_referencial_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodelo',
            name='cargos_resolucao_permitidos',
            field=models.ManyToManyField(blank=True, related_name='unidades_modelo_resolucao_cargo', to='core.cargofuncao', verbose_name='Cargos Permitidos para Resolução'),
        ),
        migrations.AddField(
            model_name='unitmodelo',
            name='permite_resolucao_flexivel',
            field=models.BooleanField(default=False, help_text='Quando marcado, esta unidade pode ser resolvida no campus com um conjunto restrito de tipos e cargos.', verbose_name='Permite Resolução Flexível no Campus'),
        ),
        migrations.AddField(
            model_name='unitmodelo',
            name='tipos_resolucao_permitidos',
            field=models.ManyToManyField(blank=True, related_name='unidades_modelo_resolucao_tipo', to='core.tipounidade', verbose_name='Tipos Permitidos para Resolução'),
        ),
        migrations.RunPython(migrate_legacy_hybrid_units, reverse_legacy_hybrid_units),
    ]
