# Generated by Django 6.0.3 on 2026-05-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_force_remove_legacy_hybrid_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regrasalteracaomodelo',
            name='departamentos_intocaveis',
            field=models.TextField(default='Gestão de Pessoas, Tecnologia da Informação, Assuntos Institucionais', help_text='Unidades que, pela Resolução CONSUP nº 44/2025, são flexíveis apenas quanto à vinculação.', verbose_name='Departamentos Restritos à Mudança de Vinculação'),
        ),
        migrations.AlterField(
            model_name='regrasalteracaomodelo',
            name='limite_flexibilizacao_fg',
            field=models.IntegerField(default=3, help_text='Limite inteiro da cota de 25% da Resolução CONSUP nº 44/2025 para alteração de nomenclatura e/ou vinculação de unidades com FG.', verbose_name='Limite Quantitativo de FGs (25%)'),
        ),
        migrations.AlterField(
            model_name='regrasalteracaomodelo',
            name='permite_regra_transicao',
            field=models.BooleanField(default=False, help_text='Aplica somente ao dimensionamento 40/26 e eleva temporariamente a cota normativa para até 5 alterações, conforme a Resolução CONSUP nº 44/2025.', verbose_name='Permitir Regra de Transição (Dim. 40/26)'),
        ),
        migrations.AlterField(
            model_name='regrasalteracaomodelo',
            name='prefixos_cargos_bloqueados',
            field=models.CharField(default='CD', help_text='Prefixos de cargos de direção que não admitem flexibilização, conforme a Resolução CONSUP nº 44/2025. Ex: CD.', max_length=255, verbose_name='Prefixos de Cargos Bloqueados'),
        ),
        migrations.AlterField(
            model_name='regrasalteracaomodelo',
            name='prefixos_cargos_flexibilizaveis',
            field=models.CharField(default='FG', help_text='Prefixos de funções gratificadas que entram na cota de 25% da Resolução CONSUP nº 44/2025. Ex: FG.', max_length=255, verbose_name='Prefixos Inclusos na Contabilização'),
        ),
        migrations.AlterField(
            model_name='regrasalteracaomodelo',
            name='verificar_sufixo_anexo',
            field=models.BooleanField(default=True, help_text='Exige preservação dos prefixos de nomenclatura do Anexo VII da Resolução CONSUP nº 44/2025.', verbose_name='Exigir Preservação de Prefixo (Anexo VII)'),
        ),
        migrations.AlterField(
            model_name='tipounidade',
            name='apenas_modelo_referencial',
            field=models.BooleanField(default=False, help_text='Quando marcado, este tipo só aparece no construtor de Modelos Referenciais - não fica disponível no builder de organogramas de campus.', verbose_name='Exclusivo para Modelos Referenciais'),
        ),
        migrations.AlterField(
            model_name='tipounidade',
            name='selecao_cargo_livre',
            field=models.BooleanField(default=False, help_text='Quando marcado, o cargo não é preenchido automaticamente - o usuário pode escolher entre os cargos disponíveis (ex: Setor/Seção que aceitam FG-01 ou FG-02).', verbose_name='Permite Seleção Livre de Cargo'),
        ),
    ]
