# Generated by Django 6.0.3 on 2026-05-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_regrasalteracaomodelo_departamentos_intocaveis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='compensar_diferentes_presentes_e_ausentes',
            field=models.BooleanField(default=True, help_text='Quando ativo, unidades FG diferentes presentes e unidades FG ausentes são compensadas para evitar dupla contagem em substituições.', verbose_name='Compensar presentes diferentes e ausentes'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='contar_unidades_fg_ausentes',
            field=models.BooleanField(default=True, help_text='Conta unidades FG previstas no modelo referencial que estejam ausentes na proposta.', verbose_name='Contar unidades FG ausentes'),
        ),
        migrations.AddField(
            model_name='regrasalteracaomodelo',
            name='contar_unidades_fg_diferentes_presentes',
            field=models.BooleanField(default=True, help_text='Conta unidades FG presentes na proposta que estejam diferentes do modelo referencial.', verbose_name='Contar unidades FG diferentes presentes'),
        ),
    ]
