# Generated by Django 6.0.3 on 2026-05-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_regrasalteracaomodelo_compensar_diferentes_presentes_e_ausentes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regrasalteracaomodelo',
            name='compensar_diferentes_presentes_e_ausentes',
        ),
        migrations.RemoveField(
            model_name='regrasalteracaomodelo',
            name='contar_unidades_fg_ausentes',
        ),
        migrations.RemoveField(
            model_name='regrasalteracaomodelo',
            name='contar_unidades_fg_diferentes_presentes',
        ),
    ]
