# Generated by Django 6.0.3 on 2026-05-05 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_regrasalteracaomodelo_compensar_diferentes_presentes_e_ausentes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimentoCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Regimento')),
                ('numero', models.CharField(blank=True, default='', max_length=100, verbose_name='Número/Ato')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='regimentos_campus/', verbose_name='Arquivo do Regimento')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Regimento')),
                ('vigente', models.BooleanField(default=False, verbose_name='Regimento Vigente')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimentos', to='core.campus')),
            ],
            options={
                'verbose_name': 'Regimento do Campus',
                'verbose_name_plural': 'Regimentos dos Campi',
                'ordering': ['campus__nome', '-vigente', '-data_publicacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompetenciaUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.CharField(blank=True, default='', max_length=50, verbose_name='Artigo')),
                ('paragrafo', models.CharField(blank=True, default='', max_length=50, verbose_name='Parágrafo')),
                ('inciso', models.CharField(blank=True, default='', max_length=50, verbose_name='Inciso')),
                ('alinea', models.CharField(blank=True, default='', max_length=50, verbose_name='Alínea')),
                ('texto', models.TextField(verbose_name='Competência')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('revisada_em', models.DateTimeField(blank=True, null=True, verbose_name='Revisada em')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_revisadas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='core.unit')),
                ('regimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias_unidades', to='core.regimentocampus')),
            ],
            options={
                'verbose_name': 'Competência da Unidade',
                'verbose_name_plural': 'Competências das Unidades',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='organograma',
            name='regimento_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organogramas', to='core.regimentocampus', verbose_name='Regimento de Referência'),
        ),
        migrations.AddConstraint(
            model_name='regimentocampus',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('campus',), name='unique_regimento_vigente_por_campus'),
        ),
    ]
