# Generated by Django 6.0.3 on 2026-05-06 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_backfill_regimentos_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolucaoEstruturaOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Resolução da Estrutura Organizacional')),
                ('numero', models.CharField(blank=True, default='', max_length=100, verbose_name='Número/Ato')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos_aprovacao/', verbose_name='Arquivo da Resolução')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link da Resolução')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resolução de Estrutura Organizacional',
                'verbose_name_plural': 'Resoluções de Estruturas Organizacionais',
                'ordering': ['campus__nome', '-data_publicacao', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='regimentocampus',
            name='unique_regimento_vigente_por_campus',
        ),
        migrations.AddField(
            model_name='regimentocampus',
            name='tipo',
            field=models.CharField(choices=[('INTERNO', 'Regimento Interno'), ('GERAL', 'Regimento Geral')], default='INTERNO', max_length=20, verbose_name='Tipo de Regimento'),
        ),
        migrations.AddConstraint(
            model_name='regimentocampus',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('campus', 'tipo'), name='unique_regimento_vigente_por_campus_tipo'),
        ),
        migrations.AddField(
            model_name='resolucaoestruturaorganizacional',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolucoes_estrutura', to='core.campus'),
        ),
        migrations.AddField(
            model_name='organograma',
            name='resolucao_estrutura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organogramas', to='core.resolucaoestruturaorganizacional', verbose_name='Resolução da Estrutura Organizacional'),
        ),
    ]
