# Generated by Django 6.0.3 on 2026-05-06 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_backfill_resolucoes_e_regimento_geral'),
    ]

    operations = [
        migrations.AddField(
            model_name='organograma',
            name='regimento_geral_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organogramas_regimento_geral', to='core.regimentocampus', verbose_name='Regimento Geral de Referência'),
        ),
    ]
