# Generated by Django 6.0.3 on 2026-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_solicitacaoalteracao_enviado_consup'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoalteracao',
            name='justificativa_avaliador',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa do Avaliador'),
        ),
        migrations.AlterField(
            model_name='solicitacaoalteracao',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('ENVIADO_CONSUP', 'Enviado para Aprovação no CONSUP'), ('DEVOLVIDO_CORRECAO', 'Devolvido para Correção'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='EM_ANALISE', max_length=20),
        ),
    ]
